-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF",
  mode = "3840x2160@60.00",
  position = "-3072x0",
  scale = 1.33333,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE 0x0B38 0x00000003",
  mode = "2560x1600@165.00",
  position = "-192x0",
  scale = 1.33333,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", persistent = true})
hl.workspace_rule({ workspace = "3", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", persistent = true})
hl.workspace_rule({ workspace = "4", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", persistent = true})
hl.workspace_rule({ workspace = "5", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", persistent = true})
hl.workspace_rule({ workspace = "6", monitor = "desc:ASUSTek COMPUTER INC ASUS PA279 0x0000B7BF", persistent = true})
hl.workspace_rule({ workspace = "7", monitor = "desc:BOE 0x0B38 0x00000003", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:BOE 0x0B38 0x00000003", persistent = true})
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE 0x0B38 0x00000003", persistent = true})
hl.workspace_rule({ workspace = "10", monitor = "desc:BOE 0x0B38 0x00000003", persistent = true})
