# BACKGROUND
background {
    #path = ~/Pictures/Wallpapers/jfo-trilla.jpg
    path = screenshot
    blur_passes = 3
    blur_sizes = 1
    brightness = 1.05
}

# GENERAL
general {
    fail_timeout = 3000
    hide_cursor = true
}

auth {
    fingerprint:enabled = true
    fingerprint:retry_delay = 150
}

label {
    text = $TIME
    font_family = Lexend Bold
    font_size = 96
    halign = left
    valign = bottom
    position = 2%, 4.3%
    shadow_passes = 1
    shadow_color = rgb(57, 57, 57)
}

label {
    font_family = Lexend, remixicon
    text = cmd[update:1000] ~/.config/hypr/Scripts/song-status.sh
    font_size = 22
    halign = left
    valign = bottom
    position = 2%, 3%
    color = rgb(153, 153, 153)
}

input-field {
    size = 500, 100
    rounding = 3
    outline_thickness = 5
    dots_size = 0.28
    dots_spacing = 0.25
    dots_rounding = 3
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text =
    fail_text =
    check_color = rgb(216, 141, 90)
    fail_color = rgb(216, 90, 90)
    capslock_color = rgb(211, 211, 211)
    font-family = Lexend
    halign = center
    fade-timeout = 1000
    valign = center
}